import Link from "next/link";
import RandomArticleLink from "@/components/random-article-link";
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import SearchBox from "@/components/SearchBox";

async function getHistory(page: number = 1) {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_API_URL}/api/history?page=${page}&limit=10`,
    { cache: "no-store" }
  );
  if (!res.ok) throw new Error("Failed to fetch history");
  return res.json();
}

export default async function HistoryPage({
  searchParams,
}: {
  searchParams?: { [key: string]: string | string[] | undefined }
}) {
  const page = parseInt(searchParams?.page?.toString() || "1");
  await getHistory(page);

  return (
    <div className="min-h-screen bg-white flex">
      {/* Sidebar with logo and navigation */}
      <aside className="w-[14rem] p-4 border-r min-h-screen text-[0.875rem] hidden lg:block">
        <div className="mb-6 flex items-center gap-2">
          <Link href="/" className="hover:opacity-80">
            <span className="font-serif text-xl">Williampedia</span>
          </Link>
        </div>
        <nav className="space-y-6">
          <div>
            <div className="font-medium mb-2 text-[#54595d]">Navigation</div>
            <ul className="space-y-1">
              <li>
                <Link
                  href="/"
                  className="text-[#36c] hover:text-[#447ff5] block py-1"
                >
                  Main page
                </Link>
              </li>
              <li>
                <Link
                  href="/history"
                  className="text-[#36c] hover:text-[#447ff5] block py-1"
                >
                  Recent changes
                </Link>
              </li>
              <li>
                <RandomArticleLink />
              </li>
              <li>
                <Link
                  href="/about"
                  className="text-[#36c] hover:text-[#447ff5] block py-1"
                >
                  About
                </Link>
              </li>
            </ul>
          </div>

        </nav>
      </aside>

      <div className="flex-1 flex flex-col">
        {/* Top Bar: Search */}
        <nav className="border-b">
          <div className="max-w-[960px] mx-auto px-4 flex justify-center items-center h-14">
            <SearchBox />
          </div>
        </nav>

        <main className="flex-1 flex justify-center">
          <div className="w-full max-w-3xl px-4 py-8">
            <div className="text-center mb-12">
              <h1 className="text-4xl font-serif mt-6 mb-2">About Williampedia</h1>
              <p className="text-lg text-muted-foreground font-serif">The AI-Generated Encyclopedia</p>
            </div>

            <div className="space-y-8 font-serif">
              <section className="prose max-w-none">
                <p>
                  Williampedia is an experimental encyclopedia where all articles are generated by William, an advanced
                  AI system. Unlike traditional encyclopedias that rely on human contributors, Williampedia showcases
                  the capabilities of artificial intelligence in creating comprehensive, well-structured knowledge
                  articles.
                </p>
              </section>

              <div className="grid md:grid-cols-2 gap-6">
                <Card>
                  <CardHeader>
                    <CardTitle className="font-serif">AI-Generated Content</CardTitle>
                    <CardDescription>Cutting-edge artificial intelligence</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">
                      Every article is created by William, ensuring consistent quality and structure. The AI system has
                      been trained on vast amounts of knowledge and can generate detailed articles on various topics.
                    </p>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle className="font-serif">Community Interaction</CardTitle>
                    <CardDescription>Engage with the content</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">
                      Readers can vote on articles, track changes through the history page, and navigate chronologically
                      through the knowledge base as it grows and evolves.
                    </p>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle className="font-serif">Continuous Updates</CardTitle>
                    <CardDescription>Always evolving</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">
                      Articles are regularly updated and improved by the AI system, incorporating new information and
                      refining existing content to ensure accuracy and relevance.
                    </p>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle className="font-serif">Transparent Process</CardTitle>
                    <CardDescription>Clear attribution</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">
                      All content is clearly marked as AI-generated, maintaining transparency about its origin. Changes
                      are tracked and timestamped in the history page for accountability.
                    </p>
                  </CardContent>
                </Card>
              </div>

              <section className="prose max-w-none mt-8">
                <h2 className="font-serif">Our Mission</h2>
                <p>
                  Williampedia aims to explore the potential of AI in knowledge creation and distribution. We believe
                  that AI can complement human knowledge work by providing structured, comprehensive information that
                  can be continuously updated and improved.
                </p>
                <p>
                  While we strive for accuracy and quality, we acknowledge that AI-generated content has its
                  limitations. We encourage users to approach the content with appropriate context and to verify
                  important information through multiple sources.
                </p>
              </section>

              <div className="border-t pt-8 mt-12">
                <h3 className="text-lg font-serif mb-4">Start Exploring</h3>
                <div className="flex flex-wrap gap-4">
                  <Button asChild variant="outline">
                    <Link href="/history">View History</Link>
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
