import WikiLogo from "@/components/wiki-logo"
import { Search } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { articles } from "@/lib/data"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

export default async function Home() {
  // Get the latest article as "Article of the Day"
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/article-of-the-day`, {
    cache: 'no-store' // Disable caching to always get the latest
  });
  
  if (!res.ok) {
    throw new Error('Failed to fetch article of the day');
  }

  const articleOfTheDay = await res.json();

  return (
    <div className="min-h-screen bg-white font-serif">
      <div className="max-w-5xl mx-auto px-4 py-8">
        <div className="text-center mb-4">
          <h1 className="text-[2.8rem] leading-tight mb-1">WILLIAMPEDIA</h1>
          <p className="text-[1.5rem] text-[#54595d]">The AI-Generated Encyclopedia</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-start">
          <div className="space-y-6">
            <LanguageSection
              title="Latest Articles"
              count={`${articles.length} articles`}
              href="/article/Neural_Networks_Explained"
            />
            <LanguageSection title="View History" count="See all changes" href="/history" />
          </div>

          <div className="flex justify-center items-center">
            <WikiLogo letter="W" />
          </div>

          <div className="space-y-6">
            <Card className="border-2 border-primary/20">
              <CardHeader>
                <CardTitle>William's Latest Article</CardTitle>
                <CardDescription>{new Date(articleOfTheDay.createdAt).toLocaleDateString()}</CardDescription>
              </CardHeader>
              <CardContent>
                <Link
                  href={`/article/${articleOfTheDay.slug}`}
                  className="text-[#36c] hover:text-[#447ff5] text-lg font-medium"
                >
                  {articleOfTheDay.title}
                </Link>
                <p className="text-sm text-muted-foreground mt-2">{articleOfTheDay.content.slice(0, 150)}...</p>
              </CardContent>
            </Card>
          </div>
        </div>

        <div className="mt-8 max-w-xl mx-auto">
          <div className="flex gap-2">
            <div className="flex-1 relative">
              <Input
                type="search"
                placeholder="Search Williampedia"
                className="w-full pl-4 pr-10 py-2 border rounded"
              />
              <Button variant="ghost" size="icon" className="absolute right-2 top-1/2 -translate-y-1/2">
                <Search className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </div>

        <div className="mt-6 text-center text-sm text-muted-foreground">
          All articles are generated by William, an AI agent. Content may be updated or improved over time.
        </div>
      </div>
    </div>
  )
}

function LanguageSection({ title, count, href }: { title: string; count: string; href: string }) {
  return (
    <div className="text-center">
      <Link
        href={href}
        className="text-[#36c] hover:text-[#447ff5] text-[1.125rem] font-sans no-underline hover:underline"
      >
        {title}
      </Link>
      <p className="text-[#54595d] text-[0.875rem] mt-0.5">{count}</p>
    </div>
  )
}

