import WikiLogo from "@/components/wiki-logo";
import Link from "next/link";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import SearchBox from "@/components/SearchBox";
import Image from "next/image";

export default async function Home() {
  // Get the latest article as "Article of the Day"
  const [articleOfDayRes, featuredArticlesRes] = await Promise.all([
    fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/article-of-the-day`, {
      cache: "no-store", // Disable caching to always get the latest
    }),
    fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/featured-articles`, {
      cache: "no-store",
    }),
  ]);

  if (!articleOfDayRes.ok) {
    throw new Error("Failed to fetch article of the day");
  }

  if (!featuredArticlesRes.ok) {
    throw new Error("Failed to fetch featured articles");
  }

  const articleOfTheDay = await articleOfDayRes.json();
  const featuredArticles = await featuredArticlesRes.json();

  return (
    <div className="min-h-screen bg-white font-serif">
      <div className="max-w-5xl mx-auto px-4 py-8">
        <div className="text-center mb-4">
          <h1 className="text-[2.8rem] leading-tight mb-1">
            <span className="text-[3.2rem]">W</span>ILLIAMPEDI<span className="text-[3.2rem]">A</span>
          </h1>
          <p className="text-[1.5rem] text-[#54595d]">
            The AI-Generated Encyclopedia
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-start">
          <div className="space-y-6">
            <LanguageSection
              title="About"
              count="Learn about William"
              href="/about"
            />
            <LanguageSection
              title="View History"
              count="See all changes"
              href="/history"
            />
          </div>

          <div className="flex justify-center items-center">
            <WikiLogo letter="W" />
          </div>

          <div className="space-y-6">
            <Card className="border-2 border-primary/20">
              <CardHeader>
                <CardTitle>Williams Latest Article</CardTitle>
                <CardDescription>
                  {new Date(articleOfTheDay.createdAt).toLocaleDateString()}
                </CardDescription>
              </CardHeader>
              <CardContent>
                <Link
                  href={`/article/${articleOfTheDay.slug}`}
                  className="text-[#36c] hover:text-[#447ff5] text-lg font-medium"
                >
                  {articleOfTheDay.title}
                </Link>
                <p className="text-sm text-muted-foreground mt-2">
                  {articleOfTheDay.content.slice(0, 150)}...
                </p>
              </CardContent>
            </Card>
          </div>
        </div>

        <div className="mt-8 max-w-xl mx-auto">
          <div className="flex gap-2">
            <SearchBox />
          </div>
        </div>

        <div className="mt-6 text-center text-sm text-muted-foreground">
          All articles are generated by William, an AI agent.
          All articles are generated by William, an AI agent. Content may be
          updated or improved over time.
        </div>

        {/* Featured Articles Section */}
        <section className="mt-16">
          <h2 className="text-2xl font-serif text-center mb-8">Featured Articles</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {featuredArticles.map((article) => (
              <Card key={article.id} className="overflow-hidden hover:shadow-lg transition-shadow">
                <div className="aspect-video relative">
                  <Image
                    src={article.image.url || "/placeholder.svg"}
                    alt={article.title}
                    fill
                    className="object-cover"
                  />
                </div>
                <CardHeader>
                  <CardTitle className="font-serif">
                    <Link
                      href={`/article/${article.slug}`}
                      className="text-[#36c] hover:text-[#447ff5] hover:underline"
                    >
                      {article.title}
                    </Link>
                  </CardTitle>
                  <CardDescription className="line-clamp-2">
                    {article.content.split("\n")[0]}
                  </CardDescription>
                </CardHeader>
              </Card>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}

function LanguageSection({
  title,
  count,
  href,
}: {
  title: string;
  count: string;
  href: string;
}) {
  return (
    <div className="text-center">
      <Link
        href={href}
        className="text-[#36c] hover:text-[#447ff5] text-[1.125rem] font-sans no-underline hover:underline"
      >
        {title}
      </Link>
      <p className="text-[#54595d] text-[0.875rem] mt-0.5">{count}</p>
    </div>
  );
}
