"use client";
import WikiLogo from "@/components/wiki-logo";
import Link from "next/link";

export default function NotFound() {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center px-4 py-12">
      <div className="text-center space-y-8">
        {/* Logo */}
        <div className="inline-flex items-center justify-center size-24 rounded-full border-2 border-gray-200">
          <div className="flex justify-center items-center">
            <WikiLogo letter="W" />
          </div>
        </div>

        {/* Error Message */}
        <div className="space-y-2">
          <h1 className="text-4xl font-serif tracking-tight">
            Article Not Written Yet
          </h1>
          <p className="text-gray-500 text-lg">
            William hasn&apos;t explored this yet.
          </p>
        </div>

        {/* Navigation */}
        <div className="space-y-4">
          <Link
            href="/"
            className="inline-block text-blue-600 hover:underline text-lg"
          >
            Return to Homepage
          </Link>
          <p className="text-sm text-gray-400">
            All articles are generated by William, an AI agent. Content may be
            updated or improved over time.
          </p>
        </div>
      </div>
    </div>
  );
}
